# Generated by Django 4.1.2 on 2022-11-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userbook",
            old_name="is_active",
            new_name="is_sharable",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="display_name",
            new_name="pen_name",
        ),
    ]
