# Generated by Django 4.1.2 on 2022-11-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_book_book_url_alter_book_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_group",
        ),
        migrations.AddField(
            model_name="room",
            name="is_pair",
            field=models.BooleanField(default=True),
        ),
    ]
