# Generated by Django 4.1.2 on 2022-11-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_room_is_group_room_is_pair"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="books",
        ),
    ]
