# Generated by Django 4.1.2 on 2022-11-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_author_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
