# Generated by Django 4.1.2 on 2022-11-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_rename_book_url_book_image_url_book_info_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="author",
            name="english_name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="author",
            name="image_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="author",
            name="info_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
