# Generated by Django 4.1.2 on 2022-11-13 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_author_description_author_english_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbook",
            name="requested_number",
        ),
        migrations.AddField(
            model_name="userbook",
            name="genre_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.genre",
            ),
        ),
        migrations.AddField(
            model_name="userbook",
            name="is_being_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userbook",
            name="my_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userbook",
            name="my_image_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="userbook",
            name="my_info_url",
            field=models.URLField(blank=True, default="", max_length=2048),
        ),
        migrations.AddField(
            model_name="userbook",
            name="my_title",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="userbook",
            name="book_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.book",
            ),
        ),
    ]
